name: Lint code
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
            version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linter
        run: pnpm run lint
