name: Run tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
            version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm run test
        env:
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
          TEST_HENTAI_VIDEO_ID: ${{ secrets.TEST_HENTAI_VIDEO_ID }}
          TEST_HENTAI_VIDEO_SLUG: ${{ secrets.TEST_HENTAI_VIDEO_SLUG }}
          TEST_HENTAI_VIDEO_TRANSCODE_FILESIZE_MBS: ${{ secrets.TEST_HENTAI_VIDEO_TRANSCODE_FILESIZE_MBS }}
          TEST_USER_CHANNEL_ID: ${{ secrets.TEST_USER_CHANNEL_ID }}
          TEST_USER_CHANNEL_SLUG: ${{ secrets.TEST_USER_CHANNEL_SLUG }}
